import jsPDF from 'jspdf';

interface QuoteItem {
  name: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

interface QuoteData {
  items: QuoteItem[];
  subtotal: number;
  discountPercent: number;
  discount: number;
  total: number;
  profitMargin: number;
}

export function generateQuotePDF(quoteData: QuoteData, title?: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Colors
  const primaryColor: [number, number, number] = [59, 130, 246];
  const textColor: [number, number, number] = [30, 41, 59];
  const mutedColor: [number, number, number] = [100, 116, 139];
  
  let y = 20;

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('QUOTE', 20, y + 8);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(title || 'Cost Estimate', 20, y + 18);
  
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 60, y + 8);
  
  y = 55;

  // Items Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(15, y, pageWidth - 30, 10, 'F');
  
  doc.setTextColor(...textColor);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Item', 20, y + 7);
  doc.text('Qty', 100, y + 7);
  doc.text('Unit Price', 120, y + 7);
  doc.text('Total', pageWidth - 40, y + 7, { align: 'right' });
  
  y += 15;

  // Items
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...textColor);
  
  quoteData.items.forEach((item) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    
    doc.setFontSize(10);
    doc.text(item.name.substring(0, 35), 20, y);
    doc.setTextColor(...mutedColor);
    doc.text(item.quantity.toString(), 100, y);
    doc.text(`$${item.unitPrice.toLocaleString()}`, 120, y);
    doc.setTextColor(...textColor);
    doc.text(`$${item.total.toLocaleString()}`, pageWidth - 40, y, { align: 'right' });
    
    y += 8;
  });

  // Line
  y += 5;
  doc.setDrawColor(226, 232, 240);
  doc.line(15, y, pageWidth - 15, y);
  y += 10;

  // Summary
  const summaryX = pageWidth - 80;
  
  doc.setFontSize(10);
  doc.setTextColor(...mutedColor);
  doc.text('Subtotal:', summaryX, y);
  doc.setTextColor(...textColor);
  doc.text(`$${quoteData.subtotal.toLocaleString()}`, pageWidth - 20, y, { align: 'right' });
  y += 8;

  if (quoteData.discount > 0) {
    doc.setTextColor(34, 197, 94);
    doc.text(`Discount (${quoteData.discountPercent}%):`, summaryX, y);
    doc.text(`-$${quoteData.discount.toLocaleString()}`, pageWidth - 20, y, { align: 'right' });
    y += 8;
  }

  // Total
  y += 2;
  doc.setFillColor(...primaryColor);
  doc.rect(summaryX - 10, y - 5, pageWidth - summaryX, 15, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', summaryX, y + 5);
  doc.text(`$${quoteData.total.toLocaleString()}`, pageWidth - 20, y + 5, { align: 'right' });

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setTextColor(...mutedColor);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by CRM System', pageWidth / 2, footerY, { align: 'center' });
  doc.text(`Profit Margin: ${quoteData.profitMargin}%`, pageWidth / 2, footerY + 5, { align: 'center' });

  // Save
  doc.save(`quote-${Date.now()}.pdf`);
}